exports.partyPrompts = [
	"Play a song you would destroy in karaoke.",
	"Name a song you would play in a high-speed car chase.",
	"Play the grooviest tune from the 80’s.",
	"Play something grimy from the 90’s.",
	"Bring back a track we forgot from the 2010’s.",
	"Play a modern classic from the 2000’s.",
	"Play a song you and your parents could both turn up to.",
	"Set the mood with your go-to preparty song.",
	"Play the song that would help you hit a new record at the gym.",
	"Name a song you have to hear played live before you die.",
	"Play a song you need to get in a mosh pit for.",
	"Name the best song to play at a tailgate.",
	"Play a song that everyone needs to know exists.",
	"Name a song that you are playing on the beach this summer.",
	"Play the song you would walk out to as a boxer.",
	"Play a song you would kill a dance battle to.",
	"Play the song that would bring you back from the dead.",
	"You just conquered the world. What’s the first song you play?",
	"Name a song that represents your city.",
	"Name a tune that takes you back to the good ol’ days.",
	"If you had to encapsulate your entire self into a song, what would it be?",
	"Name a song stronger than caffeine.",
	"Name a rhythm that will get your feet tapping.",
	"Name a song that feels like a sunny day with a clear blue sky.",
	"Name a song that feels like a powerful thunderstorm.",
	"Which song would you play to celebrate a major milestone?",
	"Name a track with an insane beat switch.",
	"If you had to pick a new national anthem, it would be…",
	"Play a track that is ridiculously braggadocious.",
	"Play an absolute banger. That’s it. That’s the prompt.",
	"Play that song that gives you goosebumps every time.",
	"Play a song that could give someone a heart attack.",
	"If they made a movie about your life, what song would be on the soundtrack?",
];
