exports.partyPrompts = [
	"Play a tune you would destroy in karaoke.",
	"You just robbed a bank. What song is fueling the ensuing car chase?",
	"Play the grooviest tune from the 80's.",
	"Play something grimy from the 90's.",
	"Bring back a track we forgot from the 2010's.",
	"Play a modern classic from the 2000's.",
	"Play a song you and your parents could both turn up to.",
	"Set the mood with your go-to pre-game song.",
	"Play the song that would help you hit a new record weight at the gym.",
	"Name a song you have to see played live before you die.",
	"Play a song you need to get in a mosh pit for.",
	"Put on the best song to play at a tailgate.",
	"Play a song that everyone needs to know exists.",
	"Put on a song that you are playing on the beach this summer.",
	"Play the song you would walk out to at your boxing match.",
	"Play a song that you would kill a dance battle to.",
	"'Play this song at my funeral to bring me back...'",
	"You just conquered the world. What's the first song you put on?",
	"Put on a song to rep your city.",
	"Name a tune that takes you back to the good ol' days.",
	"If you had to encapsulate your entire self into a song, it would be...",
	"Play a song that gives you more energy than caffeine.",
	"Play something that will get everyone's feet tapping.",
	"It's a sunny day with a clear blue sky, what song are you listening to?",
	"Name a song that feels like a thunderstorm.",
	"Which song would you play to celebrate a major milestone?",
	"Name a track that does a complete 180 half way through.",
	"Pick a new national anthem.",
	"Play something overly braggadocious.",
	"Play an absolute banger. That's it. That's the prompt.",
	"Put on that song that gives you goosebumps every time.",
	"Play a song that could give someone a heart attack.",
	"If they made a movie about your life, what song would be on the soundtrack?",
	"'I know every word to this song.'",
	"This song makes your foot a little heavier on the gas pedal...",
	"Name a song that puts you into the eye of a hurricane.",
	"Name the anthem for the apocalypse.",
	"Play a tune from the King of Pop.",
	"Play a tune from the Queen of Pop.",
	"Driving a convertible on a cliff side with the top down...",
	"Play a maaajor throwback.",
	"Get a song stuck in everyone's heads for the next two days.",
	"Select a song that's the perfect road trip soundtrack.",
	// ones below could be put into their own category
	"Listening to this song is an out-of-body experience...",
	"This song feels like a walk on a crisp autumn day...",
	"What's the first song you are playing for your first-born?",
	"A song that should only be played after midnight.",
	"'I think I'm falling in love...'",
	"Play a song that makes you feel like a kid again.",
	"Put on a song that's smoother than butter.",
	"Play a song that feels like being underwater.",
	"Play something from a different culture.",
	"Listen to this song while laying on your back and watching the stars.",
	"Play a song that might just give you super-human abilities.",
	"Put on a song that feels like the world after a fresh layer of snow.",
	"Name a song you need to close your eyes to experience fully.",
	"You can only listen to one song for the rest of your life, what is it?",
	"Name a song that would get you through a marathon.",
];
